### ISSUE TITLE
Client side error

### ISSUE THREAD

**Issue by jayessj** [ArasLabs/simple-time-sheet#1] opened 2017-06-01 15:16 UTC
I get an error message when I try to add either billable or unbillable hours. Client side error is reported

"billable_hours_D_onchangecell handler failed with message: Unable to get property 'handleItemChange' of undefined or null reference"

Strangely i also added this time sheet package to another SP5 test instance I have and it works without issue but when I import it into SP9 or indeed another SP5 DEV system I get the above error

Any ideas anyone?

**Comment by EliJDonahue** [comment] 2017-09-25 15:49
Hi jayessj,

We weren't able to reproduce the error that you are seeing. If you were not able to resolve this issue, can you confirm what browser version you are using?

Thanks!
Eli

**Comment by EliJDonahue** [comment] 2017-12-06 22:08
Closing this issue because it has not been reproduced. Will reopen the issue if someone can reproduce it and provide steps to follow.

**Closed as completed by EliJDonahue** 2017-12-06 22:08 UTC
Labels: Help Wanted
